version: '3.8'

services:
# backend service
  backend: 

    container_name: backend

    build: 
      context: .

    environment:
      - PORT=5432
      - DATABASE=myapp_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=postgres_db

    ports:
      - "80:80"

    depends_on:
      - postgres_db

# database service
  postgres_db:
    container_name: postgres_db

    image: "postgres:latest"

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp_db
      
    volumes:
      - nps_data:/var/lib/postgres/database
volumes:
  nps_data: {}